/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultsIndexRouteImport } from './routes/vaults/index'
import { Route as VaultsCreateRouteImport } from './routes/vaults/create'
import { Route as VaultsIdIndexRouteImport } from './routes/vaults/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIndexRoute = VaultsIndexRouteImport.update({
  id: '/vaults/',
  path: '/vaults/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsCreateRoute = VaultsCreateRouteImport.update({
  id: '/vaults/create',
  path: '/vaults/create',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsIdIndexRoute = VaultsIdIndexRouteImport.update({
  id: '/vaults/$id/',
  path: '/vaults/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults/': typeof VaultsIndexRoute
  '/vaults/$id/': typeof VaultsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults': typeof VaultsIndexRoute
  '/vaults/$id': typeof VaultsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vaults/create': typeof VaultsCreateRoute
  '/vaults/': typeof VaultsIndexRoute
  '/vaults/$id/': typeof VaultsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vaults/create' | '/vaults/' | '/vaults/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vaults/create' | '/vaults' | '/vaults/$id'
  id: '__root__' | '/' | '/vaults/create' | '/vaults/' | '/vaults/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VaultsCreateRoute: typeof VaultsCreateRoute
  VaultsIndexRoute: typeof VaultsIndexRoute
  VaultsIdIndexRoute: typeof VaultsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/': {
      id: '/vaults/'
      path: '/vaults'
      fullPath: '/vaults/'
      preLoaderRoute: typeof VaultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/create': {
      id: '/vaults/create'
      path: '/vaults/create'
      fullPath: '/vaults/create'
      preLoaderRoute: typeof VaultsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$id/': {
      id: '/vaults/$id/'
      path: '/vaults/$id'
      fullPath: '/vaults/$id/'
      preLoaderRoute: typeof VaultsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VaultsCreateRoute: VaultsCreateRoute,
  VaultsIndexRoute: VaultsIndexRoute,
  VaultsIdIndexRoute: VaultsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
